"""
GODMODE V8 — Developer Config Generator
Uses surplus Groq API calls to generate downloadable developer
configuration files with affiliate BaseURLs permanently baked in.
"""
from __future__ import annotations

import json
import logging
import time
from pathlib import Path
from typing import Optional

from src.core.groq_client import GroqEngine

logger = logging.getLogger(__name__)

MODELS_JSON_PATH = Path("data/models.json")
DIST_CONFIGS_DIR = Path("dist/configs")
SITE_URL = "https://llmcosts.dev"
AFFILIATE_OPENROUTER = "https://openrouter.ai/api/v1"
AFFILIATE_REF = "?ref=llmcosts"

SYSTEM_PROMPT = (
    "You are a senior ML engineer. Generate production-ready configuration files "
    "for LLM routing and inference. Be precise, include comments, and always use "
    "the cheapest appropriate model for each use-case."
)


def _load_models() -> list[dict]:
    try:
        data = json.loads(MODELS_JSON_PATH.read_text(encoding="utf-8"))
        return data.get("models", [])
    except Exception as e:
        logger.error(f"Cannot load models.json: {e}")
        return []


def _get_cheapest_by_usecase(models: list[dict]) -> dict[str, dict]:
    """Returns cheapest model for each common use-case."""
    use_case_map = {
        "coding": None,
        "rag": None,
        "chatbot": None,
        "reasoning": None,
        "vision": None,
        "bulk_processing": None,
    }

    for m in models:
        inp = m.get("pricing", {}).get("input_per_1m", 9999)
        use_cases = m.get("use_cases") or []
        capabilities = m.get("capabilities") or []

        for uc in use_case_map:
            # Check if model supports this use case
            relevant = (
                uc in " ".join(use_cases).lower()
                or uc in " ".join(capabilities).lower()
            )
            if not relevant:
                continue
            # Vision requires vision capability
            if uc == "vision" and "vision" not in capabilities:
                continue
            current = use_case_map[uc]
            if current is None or inp < current.get("pricing", {}).get("input_per_1m", 9999):
                use_case_map[uc] = m

    return {k: v for k, v in use_case_map.items() if v is not None}


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        tmp.replace(path)
    except Exception as e:
        tmp.unlink(missing_ok=True)
        raise e


def _generate_litellm_config(cheapest: dict[str, dict]) -> str:
    """Generate litellm_config.yaml with cheapest models and affiliate URLs."""
    today = time.strftime("%Y-%m-%d")
    lines = [
        f"# LiteLLM Cheapest Model Config — Generated by LLMCosts.dev",
        f"# Updated: {today}",
        f"# Source: {SITE_URL}/configs/litellm_cheapest.yaml",
        f"# Route via OpenRouter for cheapest pricing: {AFFILIATE_OPENROUTER}",
        f"",
        f"model_list:",
    ]

    for use_case, model in cheapest.items():
        mid = model.get("id", "unknown")
        name = model.get("name", "Unknown")
        inp = model.get("pricing", {}).get("input_per_1m", "N/A")
        out = model.get("pricing", {}).get("output_per_1m", "N/A")
        lines += [
            f"",
            f"  # Best for: {use_case} | Cost: ${inp}/${out} per 1M tokens",
            f"  - model_name: {use_case}-optimized",
            f"    litellm_params:",
            f"      model: openrouter/{mid}",
            f"      api_base: {AFFILIATE_OPENROUTER}",
            f"      api_key: os.environ/OPENROUTER_API_KEY",
        ]

    lines += [
        f"",
        f"general_settings:",
        f"  master_key: os.environ/LITELLM_MASTER_KEY",
        f"  # Cost tracking — see {SITE_URL} for real-time prices",
        f"",
        f"# Generated by LLMCosts.dev — {SITE_URL}",
    ]
    return "\n".join(lines)


def _generate_cursor_rules(cheapest: dict[str, dict], groq: GroqEngine) -> str:
    """Generate Cursor IDE rules using the cheapest coding model."""
    coding_model = cheapest.get("coding")
    if not coding_model:
        return ""

    mid = coding_model.get("id", "unknown")
    name = coding_model.get("name", "Unknown")
    inp = coding_model.get("pricing", {}).get("input_per_1m", "N/A")
    out = coding_model.get("pricing", {}).get("output_per_1m", "N/A")

    ai_advice = groq.generate(
        SYSTEM_PROMPT,
        f"Write 5 practical Cursor IDE rules for using {name} efficiently for coding. "
        f"Focus on prompt engineering tips to minimize token usage and cost at ${inp}/1M input.",
        max_tokens=400,
    ) or "Use concise prompts. Focus the context window. Avoid long chain-of-thought for simple tasks."

    today = time.strftime("%Y-%m-%d")
    return f"""# Cursor IDE Rules — Cost-Optimized Configuration
# Generated by LLMCosts.dev — {SITE_URL}
# Updated: {today}
# Cheapest coding model as of today: {name} (${inp}/${out} per 1M tokens)
# Route via: {AFFILIATE_OPENROUTER}

[rules]
model = openrouter/{mid}
api_base = {AFFILIATE_OPENROUTER}

# AI-Generated Optimization Tips:
{ai_advice}

# Cost Tip: Enable caching in your IDE settings to cut input costs by ~50%.
# See full comparison: {SITE_URL}/models/{coding_model.get('slug', '')}
"""


def _generate_openrouter_fallback(cheapest: dict[str, dict]) -> str:
    """Generate OpenRouter fallback chain JSON with affiliate tracking."""
    today = time.strftime("%Y-%m-%d")
    chain = {
        "_meta": {
            "generated_by": "LLMCosts.dev",
            "source": SITE_URL,
            "updated": today,
            "description": "Cost-optimized model routing chain with automatic fallbacks",
        },
        "api_base": AFFILIATE_OPENROUTER,
        "routes": [],
    }

    priority = ["coding", "reasoning", "rag", "chatbot", "bulk_processing", "vision"]
    for use_case in priority:
        model = cheapest.get(use_case)
        if model:
            chain["routes"].append({
                "use_case": use_case,
                "primary_model": model.get("id"),
                "model_name": model.get("name"),
                "input_per_1m_usd": model.get("pricing", {}).get("input_per_1m"),
                "output_per_1m_usd": model.get("pricing", {}).get("output_per_1m"),
                "fallback_model": "openai/gpt-4o-mini",
                "pricing_source": f"{SITE_URL}/models/{model.get('slug', '')}",
            })

    return json.dumps(chain, indent=2, ensure_ascii=False)


def run_config_generation() -> dict:
    """Main entry point. Generates all developer config files."""
    summary = {"configs_written": 0, "errors": 0}

    logger.info("=" * 60)
    logger.info("CONFIG GENERATOR: Building developer config files...")

    models = _load_models()
    if not models:
        summary["errors"] += 1
        return summary

    cheapest = _get_cheapest_by_usecase(models)
    logger.info(f"Cheapest models identified for {len(cheapest)} use-cases.")

    try:
        groq = GroqEngine()
    except EnvironmentError as e:
        logger.error(f"Groq unavailable: {e}")
        groq = None

    try:
        # 1. LiteLLM config
        content = _generate_litellm_config(cheapest)
        _atomic_write(DIST_CONFIGS_DIR / "litellm_cheapest.yaml", content)
        summary["configs_written"] += 1
        logger.info("  ✅ litellm_cheapest.yaml")

        # 2. Cursor Rules (requires Groq for AI tips)
        if groq and not groq.all_keys_exhausted():
            content = _generate_cursor_rules(cheapest, groq)
            if content:
                _atomic_write(DIST_CONFIGS_DIR / "cursor_rules_optimized.md", content)
                summary["configs_written"] += 1
                logger.info("  ✅ cursor_rules_optimized.md")

        # 3. OpenRouter Fallback Chain
        content = _generate_openrouter_fallback(cheapest)
        _atomic_write(DIST_CONFIGS_DIR / "openrouter_fallback_chain.json", content)
        summary["configs_written"] += 1
        logger.info("  ✅ openrouter_fallback_chain.json")

        # 4. Index page for /configs
        today = time.strftime("%Y-%m-%d")
        index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Free LLM Config Files — LLMCosts.dev</title>
<meta name="description" content="Download free, cost-optimized LLM configuration files. Updated daily by LLMCosts.dev.">
</head>
<body>
<h1>Free Developer Config Files — LLMCosts.dev</h1>
<p>Updated: {today} | <a href="{AFFILIATE_OPENROUTER}">Route via OpenRouter</a></p>
<ul>
<li><a href="litellm_cheapest.yaml">LiteLLM Cheapest Config (YAML)</a></li>
<li><a href="cursor_rules_optimized.md">Cursor IDE Rules (Markdown)</a></li>
<li><a href="openrouter_fallback_chain.json">OpenRouter Fallback Chain (JSON)</a></li>
</ul>
<p><a href="/">← Back to LLMCosts.dev</a></p>
</body>
</html>"""
        _atomic_write(DIST_CONFIGS_DIR / "index.html", index_html)
        summary["configs_written"] += 1

    except Exception as e:
        logger.error(f"Config generation error: {e}", exc_info=True)
        summary["errors"] += 1

    logger.info(f"Config generation complete: {summary}")
    return summary
